var dictionary = {
  "表头": "Header",
  "表体": "Body",
  "类别": "Type",
  "返回": "Back",
  "编码": "Code",
  "编号": "No",
  "代码": "Code",
  "搜索": "Search",
  "查询": "Search",
  "关闭": "Close",
  "备注": "Note",
  "名称": "Name",
  "重置": "Reset",
  "请输入": "Please input...",
  "请选择": "Please choose...",
  // "税则查询": "Search",
  "商品编码": "H.S.",
  "商品名称": "G-Name",
  "税则": "HS",
  "税则查询": "HS Search",
  "申报要素": "Declaration Elements",
  "申报要素查询": "Declaration Elements Search",
  "关区代码": "Customs Code",
  "关区代码查询": "Customs Code Search",
  "国家(地区)": "Country&Region",
  "国家(地区)查询": "Country&Region Search",
  "币制": "Currency",
  "币制查询": "Currency Search",
  "计量单位": "Unit",
  "计量单位查询": "Unit Search",
  "贸易方式": "Trade",
  "贸易方式查询": "Trade Search",
  "法检目录": "CIQ",
  "法检目录查询": "CIQ Search",
  "3C目录": "3C",
  "3C目录查询": "3C Search",
  "客户": "Customer",
  "客户查询": "Customer Search",
  "供应商": "Supplier",
  "供应商查询": "Supplier Search",
  "货代": "Forwarder",
  "货代查询": "Forwarder Search",
  "报关行": "Agent",
  "报关行查询": "Agent Search",
  "企业物料": "Material",
  "物料查询": "Material Search",
  "台账": "Ledger",
  "台账查询": "Ledger Search",
  "报关单": "DF",
  "手册信息": "Handbook",
  "E账册": "E-HandBook",
  "H账册": "H-HandBook",
  "设备账册": "Equipment Book",

  "今日数据": "Today's Data",
  "月度数据": "Monthly Data",
  "年度数据": "Annual Data",

  "进口数量": "Import Quantity",
  "进口金额": "Import Amount",
  "出口数量": "Export Quantity",
  "出口金额": "Export Amount",

  "月度报表": "M-Reporting",
  "进口报表": "I-Reporting",
  "出口报表": "E-Reporting",

  "厂商管理": "Vendor Management",
  "进出口管理": "I-E Management",
  "账册管理": "Book Management",
  "报表中心": "Reporting Center",

  "我的审批": "My Apply",
  "帮助与反馈": "Help&Feedback",
  "更新日志": "Update Log",
  "关于我们": "About Us",
  "分享": "Share",
  "设置": "Settings",

  "法定单位": "UOM_1",
  "第二单位": "UOM_2",
  "最惠国进口税率": "The MFN Rate of Duty",
  "普通进口税率": "Ordinary import tax rate",
  "暂定进口税率": "Temporary import tax rate",
  "消费税率": "Consumption tax",
  "出口税率": "Export tax rate",
  "出口退税率": "Export rebate rate",
  "协定税率": "Conventional tariff",
  "增值税率": "VAT Rate",
  "监管条件": "Control-MA",
  "检验检疫类别": "IQ category",

  "是否可空": "Isnull",
  "序号": "No",

  "符号": "Symbol",

  "转换率": "Conversion rate",

  "客户代码": "Customer code",
  "客户名称": "Customer name",
  "简称": "Abbreviation",
  "是否关联方": "Is affiliate",
  "联系人": "Contacts",
  "电话号码": "Tel",
  "所属国": "State",
  "地区": "Region",
  "传真": "Fax",
  "公司地址": "Company address",
  "邮政编码": "Postcode",
  "付款方式": "Terms of Payment",

  "供应商代码": "Supplier code",
  "供应商名称": "Supplier name",

  "货代代码": "Forward code",
  "货代名称": "Forward name",
  "结费标记": "Charge identification",
  "结费标识": "Charge identification",
  "涉及业务种类": "Types of business involved",
  "涉及业务类型": "Types of business involved",
  "合格类型": "Qualified type",

  "报关行代码": "Agent code",
  "报关行名称": "Agent name",
  "SAP代码": "SAP code",

  "品名": "Description",

  "物料详情": "Material details",
  "附件": "Accessory",
  "货号": "Part no",
  "货品类型": "G-Mark",
  "锁定标识": "Lock identifier",
  "HS检测": "HS detection",
  "英文品名": "ENG description",
  "企业单位": "C_UOM",
  "申报单位": "D_UOM",
  "申报比例": "D_Rate",
  "法定比例": "Rate_1",
  "第二比例": "Rate_2",
  "保税标识": "Bonded mark",
  "监管条件": "Control-MA",
  "3C标识": "3C identity",
  "商检标识": "CI identity",
  "归并标识": "Merge identity",
  "原产国": "Made In",
  "净重": "Net weight",
  "单价": "Unit price",
  "关税税率": "Rates of duty",
  "最惠国税率": "MFN tariff",
  "暂定税率": "Provisional tariff",
  "业务单元": "Business unit",
  "项目名称": "Entry name",
  "CCC证书号": "CCC No.",
  "CCC界定": "CCC Definition",
  "品牌": "Brand",
  "申请人": "Applicant",
  "申请时间": "Appl time",

  "台账编号": "Account No",
  "分提单号": "Separate B/L No",
  "厂商类型": "Vendor type",
  "厂商名称": "Vendor name",

  "内部编号": "Internal No",
  "备案号": "Handbook No",
  "主提单号": "Master order No",
  "件数": "Packages",
  "监管方式": "Trade mode",
  "合同协议号": "Contract No",
  "申报地海关": "Decl customs",
  "进出口岸": "I-E Ports",
  "启运国": "Country of origin",
  "抵运国": "Arrived in China",
  "卸货港": "Port of discharge",
  "装货港": "Port of loading",
  "境内货源地": "Domestic destination",
  "境内目的地": "Domestic destination",
  "成交方式": "Transaction mode",
  "贸易条款": "Trade clause",
  "包装种类": "Package type",
  "毛重": "Gross weight",
  "计费重": "Chargeable Weight",
  "体积": "Volume",
  "运费": "Freight Charges",
  "保费": "premium",
  "杂费": "Extras",
  "运输方式": "Type of shipping",
  "运输工具名称": "Means of transport",
  "集装箱号": "Container No",
  "许可证号": "License key",
  "业务类型": "Service type",
  "收发货人代码": "Shipper code",
  "收发货人名称": "Shipper name",
  "消费使用代码": "Consumer code",
  "消费使用名称": "Consumer name",
  "成本中心": "Cost center",
  "负责人": "Person in charge",
  "创建人": "Create people",
  "创建时间": "Create time",
  "转关报关行代码": "Trans agent code",

  "商品代码": "Item code",
  "商品名称": "Item name",
  "DN号": "DN No",
  "多项号标识": "Item identity",
  "商品货号": "Product code",
  "规格型号": "Spec Model",
  "备案项号": "Record item no",
  "项号": "G-NO",
  "备案序号": "Item No",
  "发票号": "Invoice No",
  "订单号": "PO No",
  "申报数量": "Declared quantity",
  "法定数量": "Legal quantity",
  "第二数量": "Second quantity",
  "申报单价": "Declared price",
  "申报总价": "Declared total",
  "涉证类型": "Syndrome type",
  "征免": "Exemption",
  "BOM版本号": "Bom Version No",
  "成品版本号": "Finished version No",
  "报关单统一编号": "Seq No",
  "统一编号": "Seq No",
  "报关单序号": "Declaration No",
  "原报关单号": "Original declaration No",
  "报关单号": "Decl No",
  "提运单号": "B/L No",
  "开始日期": "Start date",
  "结束日期": "End date",

  "申报日期": "Declare date",
  "申报单位名称": "Declaration name",
  "审核状态": "Audit status",
  "审核人": "Verifier",
  "审核时间": "Verifytime",
  "结案人": "Case person",
  "结案时间": "Closing time",
  "结案日期": "Closing date",
  "删改单状态": "Deletion state",
  "删改原因": "Delete reason",
  "附加编码": "Additional coding",
  "目的国": "Country of destination",
  "成交数量": "Turnover quantity",
  "成交单位": "Turnover unit",
  "成交单价": "Turnover price",
  "成交总价": "Turnover total",

  "点击查看": "Click to view",
  "料件表": "Img sheet",
  "成品表": "Exg sheet",
  "单损耗": "Consume",
  "料件归并关系": "Org img sheet",
  "成品归并关系": "Org emg sheet",
  "文档资料": "Document",
  "BOM表": "Bom sheet",

  "成品项号": "Exg_No",
  "料件项号": "Img_No",
  "版本号": "Version",


  "账册编号": "Ems_No",
  "企业内部编号": "Cop_Ems_No",
  "经营单位代码": "Trade_Code",
  "经营单位名称": "Trade_Name",
  "收发货单位代码": "Owner_Code",
  "文档上传标识": "Document upload",
  "收发货单位名称": "Owner_Name",
  "处理标志": "Processing mark",
  "单耗版本号": "Consumption version",
  "料件序号": "Img No",
  "料件名称": "Img name",
  "净耗": "Net consumption",
  "损耗率": "Rate of loss",
  "成品序号": "Exg No",
  "成品货号": "Cop Exg No",
  "成品名称": "Product name",

  "年份选择": "Year",
  "年份": "Year",
  "加载中...": "Loading...",
  "进口报关单票数": "Import declaration ticket",
  "出口报关单票数": "Export declaration ticket",
  "月份选择": "Month",
  "月份": "Month",
  "进口总数量": "I-QTY",
  "进口总金额": "I-Amount",
  "出口总数量": "E-QTY",
  "出口总金额": "E-Amount",
  "进出口总金额": "I-E-Amount",
  "数量(票)": "QTY(ticket)",
  "金额": "Amount",

  "报关单量": "Declaration QTY",

  "业务流水号": "Associated PO",

  "进出口审批": "I-E Apply",
  "账号审批": "Account apply",
  "物料审批": "Materials apply",
  "报关单审批": "Declaration apply",
  "三方账号": "Three parties apply",
  "公众号": "Official accounts",

  "您暂无权限查看此项": "You are not authorized to view this",
  "待审批": "Approval pending",
  "已审批": "Approved",
  "审核类型": "Audit type",
  "审批说明": "Approve instructions",
  "不同意": "Disagree",
  "同意": "Agree",
  "审批人": "Approver",
  "审核日期": "Audit date",

  "进出口日期": "I-E date",
  "进出日期": "I-E date",
  "索引号": "Index no",
  "海关编号": "CDF No",

  "用户ID": "User id",
  "用户名称": "User name",
  "三方昵称": "Nickname",
  "类型": "Type",

  "用户工厂": "User site",
  "用户地址": "User address",
  "用户邮箱": "User e-mail",


  "所有问题": "All the problems",
  "全部问题": "All the problems",
  "推荐文章": "Recommended articles",
  "请选择问题类型": "Please select the problem type",
  "请描述具体问题信息": "Please describe the specific information",
  "时间": "Time",
  "补充内容": "Lecture supplement",
  "联系方式": " Contact",
  "电话": "Tel",
  "选填，方便我们与您联系": "Certificate,Convenient we contact",
  "提交": "Submit",
  "快捷帮助": "Swiftness help",
  "意见反馈": "Feedback",
  "确认": "Done",
  "取消": "Close",
  "未填写": "Nothing",

  "数据问题": "Data problems",
  "系统优化": "Systems optimize",
  "系统BUG": "Systems Bug",
  "其他": "Others",

  "公司名称": "Co.Ltd.",
  "联系我们": "Tel",
  "联系地址": "Address",
  "企业介绍": "Introduce",
  "解绑账户": "Unpinless",
  "切换工厂": "Switch site",
  "账户名": "Account",
  "邮 箱": "E-mail",
  "域 名": "Domain",
  "工 厂": "Site",
  "邮箱": "E-mail",
  "域名": "Domain",
  "工厂": "Site",

  "通关参数": "Customs clearance parameters",
  "我的金关": "My Golden-Star",
  "我的账户": "My Account",

  "账册料件查询": "Img Search",
  "账册成品查询": "Exg Search",
  "账册单损耗查询": "Consume Search",
  "料件归并关系查询": "Org Img Search",
  "成品归并关系查询": "Org Exg Search",
  "BOM表查询": "Bom Search",

  "账册表头": "Header",
  "账册料件": "Img",
  "账册成品": "Exg",
  "账册单损耗": "Consume",
  "料件归并关系": "Org Img",
  "成品归并关系": "Org Exg",
  "Bom表": "Bom",

  "政策法规": "Policies & Regulations",
  "通知公告": "Notice",
  "动态信息": "News",
  "请选择CMS工厂": "Please select CMS site",
  "登录": "Login",
  "登录说明": "Login introduce",
  "正在加载中，请稍等": "Loading... Please Wait...",
  "更多": "More",
  "请输入CMS账号": "Please enter your CMS account",
  "请输入CMS密码": "Please enter your CMS password",

  "是否解除绑定？": "Do you unbind?",
  "如果解绑小程序将退出，需重新绑定后方可使用.": "If you unbind small program It will pull out and need to be rebound before it can be used.",
  "解绑成功": "Unbind succeed",
  "解绑失败": "Unbind failed",
  "用户点击取消": "Click on close",
  "微信号已绑定，未审核": "WeChat ID has been bound, unaudited",
  "警告": "Warning",
  "该用户不存在或没有工厂": "The user does not exist or does not have a site",
  "请求错误": "Request error",
  "登录的账号密码即金关之星WEB版的账号密码，登录成功后，系统将会进行小程序使用的资格审核，待审核通过后，方可使用。": "The password of the login account password is the account password of the star WEB version of jinguan. After the login, the system will be qualified for the application of the small program. After the approval is passed, the user can only use it.",
  "联系客服": "Contact customer service",
  "客户热线": "Customer Hotline",
  "您的资料正在审核中": "Your information is under review",
  "只有通过审核的账户才可以访问该小程序": "You can access the small program only through an audited account",
  "如需帮助请联系相关工作人员": "Please contact the relevant staff if you need help"
}

function translater(key) {
  if (dictionary.hasOwnProperty(key)) {
    return dictionary[key]
  }
  return key;
}

module.exports = {
  translater: translater
}